ccflags-y += -Icamera/
ccflags-y += -Icamera/common
ccflags-y += -Icamera/sensor
ccflags-y += -Icamera/sensor/cci
obj-$(CONFIG_MSMB_CAMERA)   += msm_camera_cci_i2c.o msm_camera_qup_i2c.o msm_camera_spi.o msm_camera_dt_util.o
