ccflags-y += -Icamera
ccflags-y += -Icamera/common
ccflags-y += -Icamera/msm_vb2
ccflags-y += -Icamera/camera
ccflags-y += -Icamera/sensor/io
ccflags-y += -Icamera/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += cci/ io/ csiphy/ csid/ actuator/ eeprom/ ois/ flash/
obj-$(CONFIG_MSM_CAMERA_SENSOR) += msm_sensor_init.o msm_sensor_driver.o msm_sensor.o
